In [1]:
!pip install -qqq openai  rouge-score bert-score python-dotenv pandas

In [60]:
working_dir = r"E:\MS_by_Research\SEMESTER1\research_work\Legal-Simplification\dataset_creation"

In [61]:
import openai
import pandas as pd
import time
from tqdm import tqdm
import os

In [62]:
openai.api_key = "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"

In [63]:
df = pd.read_csv(r"E:\MS_by_Research\SEMESTER1\research_work\Legal-Simplification\dataset_creation\indian_laws_large_legal_text.csv")

In [64]:
df.head()

                                          legal_text  simplified_text
0  SECTION 2 of Aadhaar (Targeted Delivery of Fin...              NaN
1  SECTION 3 of Aadhaar (Targeted Delivery of Fin...              NaN
2  SECTION 4 of Aadhaar (Targeted Delivery of Fin...              NaN
3  SECTION 7 of Aadhaar (Targeted Delivery of Fin...              NaN
4  SECTION 8 of Aadhaar (Targeted Delivery of Fin...              NaN

In [65]:
len(df)

12470

In [66]:
prompt_csv = r"E:\MS_by_Research\SEMESTER1\research_work\Legal-Simplification\Legal-Simplification\prompt.csv"

prompts = pd.read_csv(prompt_csv)
prompts.head()
print(len(prompts))

3

In [111]:
import random
def get_response(system_prompt, user_prompt):
    """Get the response from the OpenAI API."""
    os.environ["OPENAI_API_KEY"] = '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'
    client = openai.OpenAI()
    completion = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "system", "content": system_prompt},
         {"role": "user", "content": user_prompt},
                  ])

    res = completion.choices[0].message.content
  
    return res

def generate(legal_text, prompt, shot):
  """Generate the response from the OpenAI API."""

  # For zero, one, few shot learning
  prompt = pd.read_csv(prompt)
  raw_text = prompt[prompt.columns[0]].tolist()
  simplified_text = prompt[prompt.columns[1]].tolist()

  # Select a random index
  random_index = random.randint(0, len(raw_text) - 1)

  # Select a random pair of raw and simplified text
  selected_raw_text = raw_text[random_index]
  selected_simplified_text = simplified_text[random_index]

  # Give general instructions in the system prompt
  system_prompt = """You are an expert in legal text simplification."""

  if shot == 0:
    # Give more specific instructions in the user prompt and also provide the judgement text
    user_prompt = """Please simplify the given legal text:
    '''
    {}
    '''
    """.format(legal_text)

  elif shot == 1:
    # Give more specific instructions in the user prompt and also provide the judgement text
    user_prompt = f"""Below is an example of a complex legal text that has been simplified by legal experts, so that a layman person can understand. Follow the given tips to simplify legal text:
  Legal text: {selected_raw_text}
  Simplified text: {selected_simplified_text}

  Legal text: {legal_text}
  """

  elif shot == 2:
    # Give more specific instructions in the user prompt and also provide the judgement text
    user_prompt = f"""Below are examples of a legal text that have been simplified by legal experts. Follow the given tips to simplify legal text:
  1. Legal text: {raw_text[0]}
  Simplified text: {simplified_text[0]}

  2. Legal text: {raw_text[1]}
  Simplified text: {simplified_text[1]}

 Legal text: {legal_text}
  """

  elif shot == 3:
    # Give more specific instructions in the user prompt and also provide the judgement text
     user_prompt = f"""Below are examples of a legal text that have been simplified by legal experts. Follow the given tips to simplify legal text:
  1. Legal text: {raw_text[0]}
  Simplified text: {simplified_text[0]}

  2. Legal text: {raw_text[1]}
  Simplified text: {simplified_text[1]}

  3. Legal text: {raw_text[2]}
  Simplified text: {simplified_text[2]}

 Legal text: {legal_text}
  """

  elif shot == 'CoT':
    user_prompt = f"""Your task is to analyze and simplify legal provisions using a step-by-step approach.

Follow this structure:
1. **Identify key legal obligations and restrictions.**
2. **Extract the essential meaning without legal jargon.**
3. **Rewrite in plain language while keeping the full legal intent.**

Example:

Legal Text:
"Section 112(a) of the Securities and Exchange Act: 'No person shall, directly or indirectly, engage in any act, practice, or course of business that operates or would operate as a fraud or deceit upon any person in connection with the purchase or sale of securities.'"

Step 1 - Identify key points:
- Fraud and deceit in securities transactions are prohibited.
- This applies to direct and indirect actions.

Step 2 - Simplify complex legal terms:
- "Engage in any act, practice, or course of business" → "Take any action"
- "Operates or would operate as fraud or deceit" → "Is fraudulent or misleading"

Step 3 - Final Simplified Version:
"You cannot commit fraud or mislead others when buying or selling stocks."

Now, simplify the following legal text:

Legal Text: {legal_text}
"""
  else:
    raise ValueError("Invalid shot value. Please choose a value between 0 and 3.")

  response = get_response(system_prompt, user_prompt)

  # Get the response from the OpenAI API
  return response

In [49]:

test_legal_text = df.iloc[1000]['legal_text']
zero_shot_response = generate(test_legal_text, prompt_csv, 0)
one_shot_response = generate(test_legal_text, prompt_csv, 1)
two_shot_response = generate(test_legal_text, prompt_csv, 2)
three_shot_response = generate(test_legal_text, prompt_csv, 3)
CoT_response = generate(test_legal_text, prompt_csv, 'CoT')

print("Zero Shot Response: ", zero_shot_response)
print("One Shot Response: ", one_shot_response)   
print("Two Shot Response: ", two_shot_response)
print("Three Shot Response: ", three_shot_response)
print("CoT Response: ", CoT_response)

Please simplify the given legal text:
    '''
    SECTION 37 of Beedi and Cigar Workers (Conditions of Employment) Act, 1966
Beedi and Cigar Workers (Conditions of Employment) Act, 1966
37.Application of the industrial Employment

(Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 .-
(1) The provisions of the Industrial

Employment (Standing Orders) Act, 1946(20 of 1946) shall apply to every

industrial premises wherein fifty or more persons are employed or were employed

on any one day of t he preceding twelve months as if such industrial premises were

an industrial establishment to which that Act has been applied by a

notification under sub-section (3) of section 1 thereof, and as if the employee

in the said premises were a workman within the meaning of that Act.
(2) Notwithstanding anything contained in sub-section (1), the State Government

may, after giving not less than two months' notice of its intention so to do,

by notification in the Official Gazette, apply all or any of the provisions of

the Industrial Employment (Standing Orders) Act, 1946(20 of 1946), to any

industrial premises wherein less than fifty employees are employed or were

employed on any one day of the preceding twelve months as if such industrial

premises were an industrial establishment to which that Act has been applied by

a notification under sub-section (3) of section 1 thereof, and as if the

employee in the said premises were a workman within the meaning of that Act.
(3) Notwithstanding anything contained in the maternity Benefit Act, 1961(53 of

1961), the provisions of that Act shall apply to every establishment as if such

establishment were an establishment to which that Act has been applied by a

notification under sub-section (1) of section 2 thereof:

Provided that the said Act shall, in its application to a home worker,

apply subject to the following modifications, namely:--
(a) in section 5, in the Explanation to

sub-section (1), the words "or one rupee a day, whichever is higher"

shall be omitted; and
(b) sections 8 and 10 shall be omitted
    '''

Section 37 of the Beedi and Cigar Workers (Conditions of Employment) Act, 1966 talks about the application of the Industrial Employment (Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 to industrial premises and establishments. It states that the Industrial Employment (Standing Orders) Act, 1946 should apply to industrial premises with fifty or more employees, and the State Government may decide to apply it to premises with less than fifty employees. It also clarifies that the Maternity Benefit Act, 1961 applies to all establishments, with some specific modifications for home workers.
Below is an example of a complex legal text that has been simplified by legal experts, so that a layman person can understand. Follow the given tips to simplify legal text:
  Legal text: Monitoring, information gathering etc

(1) The economic regulator must keep under review the carrying on in the United Kingdom and elsewhere of the following activities—

(a)operating a site for the disposal of carbon dioxide by way of geological storage.

(b)providing a service of transporting carbon dioxide by a licensable means of transportation.

(c)activities ancillary to activities mentioned in paragraph (a) or (b).

(2) The economic regulator may, for the purpose of facilitating the performance of its functions under this Part, collect information with respect to such activities.

(3) The economic regulator must give the Secretary of State or the CMA any information they may request with respect to any matter relating to the economic regulator’s functions under this Part.
  Simplified text: Review Activities: The economic regulator must regularly check and assess activities in the UK and possibly abroad regarding:

The operation of sites for burying carbon dioxide underground (geological storage).

The service of transporting carbon dioxide using methods that require a license.

Any additional activities that support the above two points.

Collect Information: For the purpose of doing its job well, the economic regulator can gather information about these activities.

Share Information: The economic regulator must provide information to the Secretary of State or the Competition and Markets Authority (CMA) if they ask for it, as long as it's about something related to the regulator's duties in this area.

  Legal text: SECTION 37 of Beedi and Cigar Workers (Conditions of Employment) Act, 1966
Beedi and Cigar Workers (Conditions of Employment) Act, 1966
37.Application of the industrial Employment

(Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 .-
(1) The provisions of the Industrial

Employment (Standing Orders) Act, 1946(20 of 1946) shall apply to every

industrial premises wherein fifty or more persons are employed or were employed

on any one day of t he preceding twelve months as if such industrial premises were

an industrial establishment to which that Act has been applied by a

notification under sub-section (3) of section 1 thereof, and as if the employee

in the said premises were a workman within the meaning of that Act.
(2) Notwithstanding anything contained in sub-section (1), the State Government

may, after giving not less than two months' notice of its intention so to do,

by notification in the Official Gazette, apply all or any of the provisions of

the Industrial Employment (Standing Orders) Act, 1946(20 of 1946), to any

industrial premises wherein less than fifty employees are employed or were

employed on any one day of the preceding twelve months as if such industrial

premises were an industrial establishment to which that Act has been applied by

a notification under sub-section (3) of section 1 thereof, and as if the

employee in the said premises were a workman within the meaning of that Act.
(3) Notwithstanding anything contained in the maternity Benefit Act, 1961(53 of

1961), the provisions of that Act shall apply to every establishment as if such

establishment were an establishment to which that Act has been applied by a

notification under sub-section (1) of section 2 thereof:

Provided that the said Act shall, in its application to a home worker,

apply subject to the following modifications, namely:--
(a) in section 5, in the Explanation to

sub-section (1), the words "or one rupee a day, whichever is higher"

shall be omitted; and
(b) sections 8 and 10 shall be omitted

Application of Laws:

(1) If an industrial premises employs or had employed fifty or more people on any day in the past year, the Industrial Employment (Standing Orders) Act, 1946 will apply to it, and its workers will be considered as workmen under that Act.

(2) Even if an industrial premises employs less than fifty people, the State Government can decide to apply some or all of the provisions of the Industrial Employment (Standing Orders) Act, 1946 to it, and its workers will be considered as workmen under that Act.

(3) The Maternity Benefit Act, 1961 will apply to every establishment, with the exception of home workers who will have some particular parts of the Act modified.
Below are examples of a legal text that have been simplified by legal experts. Follow the given tips to simplify legal text:
  1. Legal text: Principal objectives and general duties of Secretary of State and economic regulator
(1) The principal objectives of the Secretary of State and the GEMA in carrying out their respective functions under this Part are to—
(a)protect the interests of current and future transport and storage network users.
(b)protect the interests of any consumers whose interests the Secretary of State or the economic regulator (as the case may be) considers may be impacted by the exercise of their respective functions under this Part.
(c)promote the efficient and economic development and operation of transport and storage networks, having regard to the need for license holders to be able to finance their licensable activities.
(2) In this Part the GEMA is referred to as the “economic regulator”.
(3) The Secretary of State and the economic regulator must carry out their respective functions under this Part in the manner which the Secretary of State or the economic regulator (as the case may be) considers is best calculated to further the principal objectives, wherever appropriate by—
(a)promoting effective competition between persons engaged in, or in commercial activities connected with, the activities mentioned in section 2(2);
(b)promoting the resilience of transport and storage networks.
(c)protecting the public from dangers arising from the construction, operation and decommissioning of infrastructure used for the purposes of activities mentioned in section 2(2).
  Simplified text: Principal Objectives:
Users: They need to look out for the interests of people who currently use, and who will use in the future, the transport and storage networks.
Protect Consumers: They should also protect the interests of consumers who might be affected by their decisions and actions under this law.
Promote Efficiency and Economy: They should encourage the development and operation of transport and storage networks in an efficient and economical way. This includes making sure that the companies who hold licenses for these activities have enough money to carry them out.
General Duties:
The Secretary of State and the economic regulator must perform their duties in a way that they believe will best achieve these objectives. This may include:
Encouraging Competition: Promoting competition among companies involved in the transport and storage networks or related commercial activities.
Ensuring Resilience: Making sure that transport and storage networks are robust and reliable.
Protecting the Public: Safeguarding the public from any dangers that might arise from building, operating, or decommissioning infrastructure related to these networks.

  2. Legal text: Monitoring, information gathering etc

(1) The economic regulator must keep under review the carrying on in the United Kingdom and elsewhere of the following activities—

(a)operating a site for the disposal of carbon dioxide by way of geological storage.

(b)providing a service of transporting carbon dioxide by a licensable means of transportation.

(c)activities ancillary to activities mentioned in paragraph (a) or (b).

(2) The economic regulator may, for the purpose of facilitating the performance of its functions under this Part, collect information with respect to such activities.

(3) The economic regulator must give the Secretary of State or the CMA any information they may request with respect to any matter relating to the economic regulator’s functions under this Part.
  Simplified text: Review Activities: The economic regulator must regularly check and assess activities in the UK and possibly abroad regarding:

The operation of sites for burying carbon dioxide underground (geological storage).

The service of transporting carbon dioxide using methods that require a license.

Any additional activities that support the above two points.

Collect Information: For the purpose of doing its job well, the economic regulator can gather information about these activities.

Share Information: The economic regulator must provide information to the Secretary of State or the Competition and Markets Authority (CMA) if they ask for it, as long as it's about something related to the regulator's duties in this area.

 Legal text: SECTION 37 of Beedi and Cigar Workers (Conditions of Employment) Act, 1966
Beedi and Cigar Workers (Conditions of Employment) Act, 1966
37.Application of the industrial Employment

(Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 .-
(1) The provisions of the Industrial

Employment (Standing Orders) Act, 1946(20 of 1946) shall apply to every

industrial premises wherein fifty or more persons are employed or were employed

on any one day of t he preceding twelve months as if such industrial premises were

an industrial establishment to which that Act has been applied by a

notification under sub-section (3) of section 1 thereof, and as if the employee

in the said premises were a workman within the meaning of that Act.
(2) Notwithstanding anything contained in sub-section (1), the State Government

may, after giving not less than two months' notice of its intention so to do,

by notification in the Official Gazette, apply all or any of the provisions of

the Industrial Employment (Standing Orders) Act, 1946(20 of 1946), to any

industrial premises wherein less than fifty employees are employed or were

employed on any one day of the preceding twelve months as if such industrial

premises were an industrial establishment to which that Act has been applied by

a notification under sub-section (3) of section 1 thereof, and as if the

employee in the said premises were a workman within the meaning of that Act.
(3) Notwithstanding anything contained in the maternity Benefit Act, 1961(53 of

1961), the provisions of that Act shall apply to every establishment as if such

establishment were an establishment to which that Act has been applied by a

notification under sub-section (1) of section 2 thereof:

Provided that the said Act shall, in its application to a home worker,

apply subject to the following modifications, namely:--
(a) in section 5, in the Explanation to

sub-section (1), the words "or one rupee a day, whichever is higher"

shall be omitted; and
(b) sections 8 and 10 shall be omitted

Simplified text:
Application of Labor Laws to Industrial Premises and Workers

The Industrial Employment (Standing Orders) Act of 1946 and the Maternity Benefit Act of 1961 apply to industrial premises and workers as follows:

1. Standing Orders Act Application:
   - The Standing Orders Act applies to industrial premises with 50 or more employees as if it were an established industrial site. It also applies to the employees as if they were considered workers under that Act.
   - The state government can also apply provisions of the Act to industrial premises with less than fifty employees by giving notice.

2. Maternity Benefit Act Application:
   - The Maternity Benefit Act applies to every establishment as if it were designated under the Act. Home workers are also subject to this Act with specified modifications.

Note: Certain sections have been omitted or modified for the application to home workers.
Below are examples of a legal text that have been simplified by legal experts. Follow the given tips to simplify legal text:
  1. Legal text: Principal objectives and general duties of Secretary of State and economic regulator
(1) The principal objectives of the Secretary of State and the GEMA in carrying out their respective functions under this Part are to—
(a)protect the interests of current and future transport and storage network users.
(b)protect the interests of any consumers whose interests the Secretary of State or the economic regulator (as the case may be) considers may be impacted by the exercise of their respective functions under this Part.
(c)promote the efficient and economic development and operation of transport and storage networks, having regard to the need for license holders to be able to finance their licensable activities.
(2) In this Part the GEMA is referred to as the “economic regulator”.
(3) The Secretary of State and the economic regulator must carry out their respective functions under this Part in the manner which the Secretary of State or the economic regulator (as the case may be) considers is best calculated to further the principal objectives, wherever appropriate by—
(a)promoting effective competition between persons engaged in, or in commercial activities connected with, the activities mentioned in section 2(2);
(b)promoting the resilience of transport and storage networks.
(c)protecting the public from dangers arising from the construction, operation and decommissioning of infrastructure used for the purposes of activities mentioned in section 2(2).
  Simplified text: Principal Objectives:
Users: They need to look out for the interests of people who currently use, and who will use in the future, the transport and storage networks.
Protect Consumers: They should also protect the interests of consumers who might be affected by their decisions and actions under this law.
Promote Efficiency and Economy: They should encourage the development and operation of transport and storage networks in an efficient and economical way. This includes making sure that the companies who hold licenses for these activities have enough money to carry them out.
General Duties:
The Secretary of State and the economic regulator must perform their duties in a way that they believe will best achieve these objectives. This may include:
Encouraging Competition: Promoting competition among companies involved in the transport and storage networks or related commercial activities.
Ensuring Resilience: Making sure that transport and storage networks are robust and reliable.
Protecting the Public: Safeguarding the public from any dangers that might arise from building, operating, or decommissioning infrastructure related to these networks.

  2. Legal text: Monitoring, information gathering etc

(1) The economic regulator must keep under review the carrying on in the United Kingdom and elsewhere of the following activities—

(a)operating a site for the disposal of carbon dioxide by way of geological storage.

(b)providing a service of transporting carbon dioxide by a licensable means of transportation.

(c)activities ancillary to activities mentioned in paragraph (a) or (b).

(2) The economic regulator may, for the purpose of facilitating the performance of its functions under this Part, collect information with respect to such activities.

(3) The economic regulator must give the Secretary of State or the CMA any information they may request with respect to any matter relating to the economic regulator’s functions under this Part.
  Simplified text: Review Activities: The economic regulator must regularly check and assess activities in the UK and possibly abroad regarding:

The operation of sites for burying carbon dioxide underground (geological storage).

The service of transporting carbon dioxide using methods that require a license.

Any additional activities that support the above two points.

Collect Information: For the purpose of doing its job well, the economic regulator can gather information about these activities.

Share Information: The economic regulator must provide information to the Secretary of State or the Competition and Markets Authority (CMA) if they ask for it, as long as it's about something related to the regulator's duties in this area.

  3. Legal text: Power to create license types.

(1)The Secretary of State may by regulations provide that different types of license may be granted under section 7(1) in respect of different descriptions of activity falling within section 2(2).

(2) Regulations under this section may make consequential, transitional, incidental or supplementary provision including—

(a)amendments (or repeals or revocations) in any provision of this Act or any other enactment, and

(b)provision modifying any standard conditions of licences or provision determining the conditions which are to be standard conditions for the purposes of new types of licences.

(3) Before making regulations under this section containing provision within devolved competence, the Secretary of State must give notice to each relevant devolved authority—

(a)stating that the Secretary of State proposes to make regulations under this section, and

(b)specifying the period (of not less than 28 days from the date on which the notice is given) within which representations may be made with respect to the provision within the relevant devolved competence,


In [50]:
print("Zero Shot Response: ", zero_shot_response)

Zero Shot Response:  Section 37 of the Beedi and Cigar Workers (Conditions of Employment) Act, 1966 talks about the application of the Industrial Employment (Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 to industrial premises and establishments. It states that the Industrial Employment (Standing Orders) Act, 1946 should apply to industrial premises with fifty or more employees, and the State Government may decide to apply it to premises with less than fifty employees. It also clarifies that the Maternity Benefit Act, 1961 applies to all establishments, with some specific modifications for home workers.

In [51]:
print("One Shot Response: ", one_shot_response)

One Shot Response:  Application of Laws:

(1) If an industrial premises employs or had employed fifty or more people on any day in the past year, the Industrial Employment (Standing Orders) Act, 1946 will apply to it, and its workers will be considered as workmen under that Act.

(2) Even if an industrial premises employs less than fifty people, the State Government can decide to apply some or all of the provisions of the Industrial Employment (Standing Orders) Act, 1946 to it, and its workers will be considered as workmen under that Act.

(3) The Maternity Benefit Act, 1961 will apply to every establishment, with the exception of home workers who will have some particular parts of the Act modified.

In [52]:
print("Two Shot Response: ", two_shot_response)

Two Shot Response:  Simplified text:
Application of Labor Laws to Industrial Premises and Workers

The Industrial Employment (Standing Orders) Act of 1946 and the Maternity Benefit Act of 1961 apply to industrial premises and workers as follows:

1. Standing Orders Act Application:
   - The Standing Orders Act applies to industrial premises with 50 or more employees as if it were an established industrial site. It also applies to the employees as if they were considered workers under that Act.
   - The state government can also apply provisions of the Act to industrial premises with less than fifty employees by giving notice.

2. Maternity Benefit Act Application:
   - The Maternity Benefit Act applies to every establishment as if it were designated under the Act. Home workers are also subject to this Act with specified modifications.

Note: Certain sections have been omitted or modified for the application to home workers.

In [53]:
print("Three Shot Response: ", three_shot_response)

Three Shot Response:  Application of Industrial Laws:
The Industrial Employment (Standing Orders) Act, 1946 applies to industrial premises with 50 or more employees as if it were an industrial establishment. The State Government may also apply this Act to premises with fewer than 50 employees. Additionally, the Maternity Benefit Act, 1961 applies to all establishments and includes specific modifications for home workers.

In [54]:
print("CoT Response: ", CoT_response)

CoT Response:  Section 37 of Beedi and Cigar Workers (Conditions of Employment) Act, 1966

The Industrial Employment (Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 apply to workplaces with 50 or more employees. State Governments can extend these acts to workplaces with fewer employees through an official notification. The Maternity Benefit Act applies to all establishments, with some specific modifications for home workers.

In [58]:

CoT_response = generate(test_legal_text, prompt_csv, 'CoT')

Your task is to analyze and simplify legal provisions using a step-by-step approach.

Follow this structure:
1. **Identify key legal obligations and restrictions.**
2. **Extract the essential meaning without legal jargon.**
3. **Rewrite in plain language while keeping the full legal intent.**

Example:

Legal Text:
"Section 112(a) of the Securities and Exchange Act: 'No person shall, directly or indirectly, engage in any act, practice, or course of business that operates or would operate as a fraud or deceit upon any person in connection with the purchase or sale of securities.'"

Step 1 - Identify key points:
- Fraud and deceit in securities transactions are prohibited.
- This applies to direct and indirect actions.

Step 2 - Simplify complex legal terms:
- "Engage in any act, practice, or course of business" → "Take any action"
- "Operates or would operate as fraud or deceit" → "Is fraudulent or misleading"

Step 3 - Final Simplified Version:
"You cannot commit fraud or mislead others when buying or selling stocks."

Now, simplify the following legal text:

Legal Text: SECTION 37 of Beedi and Cigar Workers (Conditions of Employment) Act, 1966
Beedi and Cigar Workers (Conditions of Employment) Act, 1966
37.Application of the industrial Employment

(Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 .-
(1) The provisions of the Industrial

Employment (Standing Orders) Act, 1946(20 of 1946) shall apply to every

industrial premises wherein fifty or more persons are employed or were employed

on any one day of t he preceding twelve months as if such industrial premises were

an industrial establishment to which that Act has been applied by a

notification under sub-section (3) of section 1 thereof, and as if the employee

in the said premises were a workman within the meaning of that Act.
(2) Notwithstanding anything contained in sub-section (1), the State Government

may, after giving not less than two months' notice of its intention so to do,

by notification in the Official Gazette, apply all or any of the provisions of

the Industrial Employment (Standing Orders) Act, 1946(20 of 1946), to any

industrial premises wherein less than fifty employees are employed or were

employed on any one day of the preceding twelve months as if such industrial

premises were an industrial establishment to which that Act has been applied by

a notification under sub-section (3) of section 1 thereof, and as if the

employee in the said premises were a workman within the meaning of that Act.
(3) Notwithstanding anything contained in the maternity Benefit Act, 1961(53 of

1961), the provisions of that Act shall apply to every establishment as if such

establishment were an establishment to which that Act has been applied by a

notification under sub-section (1) of section 2 thereof:

Provided that the said Act shall, in its application to a home worker,

apply subject to the following modifications, namely:--
(a) in section 5, in the Explanation to

sub-section (1), the words "or one rupee a day, whichever is higher"

shall be omitted; and
(b) sections 8 and 10 shall be omitted

Step 1 - Identify key points:
- Application of the Industrial Employment (Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 to specific industrial premises.
- Determining the applicability based on the number of employees.
- Specific modifications to the Maternity Benefit Act for home workers.

Step 2 - Simplify complex legal terms:
- "Industrial premises wherein fifty or more persons are employed" → "Places with 50 or more employees"
- "Provisions of the Industrial Employment (Standing Orders) Act, 1946 shall apply" → "Rules from the Industrial Employment Act (1946) will apply"
- "The provisions of that Act shall apply to every establishment" → "The rules of that Act apply to all workplaces"

Step 3 - Final Simplified Version:
"The rules from the Industrial Employment Act (1946) will apply to workplaces with 50 or more employees. The Maternity Benefit Act applies to all workplaces, with specific changes for home workers."

In [59]:
print("CoT Response: ", CoT_response)

CoT Response:  Step 1 - Identify key points:
- Application of the Industrial Employment (Standing Orders) Act, 1946 and the Maternity Benefit Act, 1961 to specific industrial premises.
- Determining the applicability based on the number of employees.
- Specific modifications to the Maternity Benefit Act for home workers.

Step 2 - Simplify complex legal terms:
- "Industrial premises wherein fifty or more persons are employed" → "Places with 50 or more employees"
- "Provisions of the Industrial Employment (Standing Orders) Act, 1946 shall apply" → "Rules from the Industrial Employment Act (1946) will apply"
- "The provisions of that Act shall apply to every establishment" → "The rules of that Act apply to all workplaces"

Step 3 - Final Simplified Version:
"The rules from the Industrial Employment Act (1946) will apply to workplaces with 50 or more employees. The Maternity Benefit Act applies to all workplaces, with specific changes for home workers."

In [117]:


print(len(df))
test_df = df.iloc[50:100]
print(len(test_df))
test_df.head()

12470
50

                                           legal_text  simplified_text
50  SECTION 8 of Acquired Territories (Merger) Act...              NaN
51  SECTION 11 of Acquired Territories (Merger) Ac...              NaN
52  SECTION 4 of Acquisition of Certain Area at Ay...              NaN
53  SECTION 6 of Acquisition of Certain Area at Ay...              NaN
54  SECTION 7 of Acquisition of Certain Area at Ay...              NaN

In [118]:
output_file = r"E:\MS_by_Research\SEMESTER1\research_work\Legal-Simplification\dataset_creation\INDIAN_LAW_DATASET.csv"
import csv 
with open(output_file, 'a') as f:
    writer = csv.writer(f)
    for index, row in tqdm(test_df.iterrows(), total=len(test_df)):
        if pd.isna(row['simplified_text']) or not row['simplified_text']:
            legal_text = row['legal_text']
            two_shot_response = generate(legal_text, prompt_csv, 2)
            writer.writerow([legal_text, two_shot_response])

100%|██████████| 50/50 [01:51<00:00,  2.22s/it]

In [120]:

df_output = pd.read_csv(output_file)
df_output.head()
print(len(df_output))

100

In [109]:
#print last row of the output file
print(df_output.tail(1))

                                           legal_text  \
49  SECTION 6 of Acquired Territories (Merger) Act...

                                      simplified_text
49  Section 6 of the Acquired Territories (Merger)...